# ====================== Stage 1: Build ======================
FROM maven:3.9.5-eclipse-temurin-17 AS build
WORKDIR /email

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

# ====================== Stage 2: Runtime ======================
FROM eclipse-temurin:17-jre
WORKDIR /email

COPY --from=build /email/target/*.jar app.jar

EXPOSE 9091
ENTRYPOINT ["java", "-jar", "app.jar"]
